import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/signin': 'http://localhost:4200',
      '/adminSignup': 'http://localhost:4200',
      '/forgot-password': 'http://localhost:4200',
      '/verify-pin': 'http://localhost:4200',
      '/reset-forgotten-password': 'http://localhost:4200',
      '/profile': 'http://localhost:4200',
      '/allAdmins': 'http://localhost:4200',
      '/allUsers': 'http://localhost:4200',
      '/AdminUpdate': 'http://localhost:4200',
      '/UserUpdate': 'http://localhost:4200',
      '/deleteAdmin': 'http://localhost:4200',
      '/updateStatus': 'http://localhost:4200',
      '/resetPassword': 'http://localhost:4200',
      '/adminAuth': 'http://localhost:4200',
      '/protected': 'http://localhost:4200',
      '/meters-information': 'http://localhost:4200',
      '/meter-summary': 'http://localhost:4200',
      '/activeInactiveMeters': 'http://localhost:4200',
      '/totalMeters': 'http://localhost:4200',
      '/meterWeekAndMonthData': 'http://localhost:4200',
      '/meterDataByDRN': 'http://localhost:4200',
      '/allProcessedTokensByDRN': 'http://localhost:4200',
      '/getAllProcessedTokensByDRN': 'http://localhost:4200',
      '/gridTopology': 'http://localhost:4200',
      '/total-tranformers': 'http://localhost:4200',
      '/energy-time-periods': 'http://localhost:4200',
      '/currentDayEnergy': 'http://localhost:4200',
      '/weeklyDataAmount': 'http://localhost:4200',
      '/yearly': 'http://localhost:4200',
      '/weekly': 'http://localhost:4200',
      '/hourlyPowerConsumption': 'http://localhost:4200',
      '/average-current-voltage': 'http://localhost:4200',
      '/last-apparent-power': 'http://localhost:4200',
      '/suburb-time-periods': 'http://localhost:4200',
      '/search-by-weekly-power': 'http://localhost:4200',
      '/search-by-monthly-power': 'http://localhost:4200',
      '/finance': 'http://localhost:4200',
      '/tokenAmount': 'http://localhost:4200',
      '/totalTokensBought': 'http://localhost:4200',
      '/get-system-processed-tokens': 'http://localhost:4200',
      '/getAll': 'http://localhost:4200',
      '/criticalNotifications': 'http://localhost:4200',
      '/notificationsByDRN': 'http://localhost:4200',
      '/notificationTypes': 'http://localhost:4200',
      '/notificationsTypesByDRN': 'http://localhost:4200',
      '/emergencyNotifications': 'http://localhost:4200',
      '/respond': 'http://localhost:4200',
      '/deleteNotifications': 'http://localhost:4200',
      '/meterPercentageCount': 'http://localhost:4200',
      '/systemSettings': 'http://localhost:4200',
      '/settings': 'http://localhost:4200',
      '/suburbEnergy': 'http://localhost:4200',
      '/meter-registration': 'http://localhost:4200',
      '/healthCheck': 'http://localhost:4200',
      '/cb/vending': 'http://localhost:4200',
      '/api/v1/meter-health': 'http://localhost:4200',
      '/api/v1/relay-events': 'http://localhost:4200',
      '/api': 'http://localhost:4200',
    },
  },
})
